format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch]($style) "
style = "bold mauve"

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "
